#!/bin/bash
#
#   ybs-integrity-check -- integrity check of ybs tree.  
#
#   Copyright © 2012 ivali.com
#   Maintainer: Zhongxin Huang <huangzhongxin@ivali.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

. /usr/lib/ybs/funcs

show_usage() {
    cat <<EOF
    $0 - integrity check of ybs tree.

    Usage: $0 pbslib-dir

EOF
}

raw_check() {
    local app="$1"; shift
    local deps="$@"
    local dep

    for dep in $deps; do
        dep="${dep/-dev/}"
        dep="${dep//(*)}"
        pbsfile=$(ybs_show "$dep" pbs)    
        if [ -f "$pbsfile" ];  then
            atom_parse "$pbsfile"
            if [ "x$dep" != "x$N" ]; then
                . "$pbsfile"
                str_isin "$PROVIDE" "$dep" || echo "$app --> $dep"
            fi
        else
            echo "$app --> $dep"
        fi
    done    
}

#
case x$1 in
    x*h|x*help)
        show_usage
        exit 0
esac

case x$# in 
    x0) PBSLIB_PATH=$PBSLIB_PATH ;;
    x1) PBSLIB_PATH=$(readlink -f $1) ;;
  x2|*) show_usage
        exit 0
esac

if [ ! -d $PBSLIB_PATH ]; then
    die "$PBSLIB_PATH not found."
fi

# Main
echo ================================================
echo = Integrity Check $YARCH of $PBSLIB_PATH =
echo ================================================

cd $PBSLIB_PATH

echo
echo Missing pbs files
echo --------------------

ls -1d */* |while read app; do
    ls "$app"/*.pbs 2>/dev/null 1>&2 || ( [ -d "$app" ] && echo "$app" )
done

echo
echo Missing Runtime Dependencies
echo ----------------------

ls -1d */* |while read app; do
    pbsfile=$(ybs_show "$app" pbs)
    [ -f "$pbsfile" ] && . "$pbsfile"
    raw_check $app $RDEPEND        
done 

echo
echo Missing Make Dependencies
echo ----------------------

ls -1d */* |while read app; do
    pbsfile=$(ybs_show "$app" pbs)
    [ -f "$pbsfile" ] && . "$pbsfile"
    raw_check $app $BDEPEND
done

# End of file
