#!/bin/bash
#

dofont() {
    local i
    for i in "$@"; do
        if [ -d "$i" ]; then
            echo "mkfontscale $i"
	        mkfontscale "$i"
	        echo "mkfontdir $i"
	        mkfontdir  "$i"
	        echo "fc-cache $i"
	        fc-cache -f "$i"
        else    
            echo "dofont: cannot access $i: No such file or directory"
            return 1
        fi
    done
}

dofont "$@"
