#!/bin/bash
#
#

doinstall_info () {
    echo "install info: $@"
    [ -x /usr/bin/install-info ] || return 0
    local i infodir=/usr/share/info
    for i in $@; do
        install-info "$infodir"/"$i" $infodir/dir 2>/dev/null
    done
    return 0
}

doinstall_info $@
