#!/bin/bash
#
#

doinstall_info () {
    local i infodir="/usr/share/info"
    echo "install info: $@"
    for i in "$@"; do
        install-info $infodir/"$i" $infodir/dir || return 1
    done
}

doinstall_info "$@"
