#!/usr/bin/env python
#
#

import os
import sys

if __name__ == '__main__':
    args = sys.argv[1:]
    end = args[-1]
    end = os.path.realpath(end)
    target_dir = os.path.dirname(end)
    os.system('mkdir -p'+' '+target_dir)
    for i in args[0:-1]:
        i = '"' + i + '"'
        os.system('mv '+' '+i+' '+end)
