#!/usr/bin/env python
#
#

import os
import sys

if __name__ == '__main__':
    args = sys.argv[1:]
    target_dir = args[-1]
    os.system('mkdir -p' + ' ' + target_dir)
    for i in args[0:-1]:
        i = '"' + i + '"'
        os.system('mv ' + ' ' + i + ' ' + target_dir)
