#!/bin/bash
#
#

doremove_info () {
    echo "remove info: $@"
    [ -x /usr/bin/install-info ] || return 0
    local i infodir=/usr/share/info
    for i in $@; do
        install-info --delete "$infodir"/"$i" $infodir/dir 2>/dev/null
    done
    return 0
}

doremove_info $@
