#!/bin/bash
#
#

glib_compile_schemas() {
    if [ -x /usr/bin/glib-compile-schemas ]; then
        echo "glib-compile-schemas /usr/share/glib-2.0/schemas"
	    glib-compile-schemas /usr/share/glib-2.0/schemas
    else
        echo ":( /usr/bin/glib-compile-schemas not found."
        return 1
    fi
    return 0
}

glib_compile_schemas
