#!/bin/bash
#
#

gnome2_install_defaut_gconf() {
    local t=$1 # Type
    local n=$2 # Name
    local v=$3 # Value
    
    echo "Setting: \"$n\" \"$v\""
    configfile=$(gconftool-2 --get-default-source)
    if [ "x$t" = "xlist" ];then
        gconftool-2 --direct --config-source="$configfile" --type list --set "$n" --list-type string "$v" || return 1
	else
	    gconftool-2 --direct --config-source="$configfile" --type "$t" --set "$n" "$v" || return 1
    fi
}

gnome2_install_defaut_gconf "$@"
