#!/bin/bash
#
#

gnome2_uninstall_schema() {
    # This is this-is-deprecated
    # return 0
    local schemas="$@"
    for schema in $schemas; do
	    echo "Uninstalling: $schema"
	    GCONF_CONFIG_SOURCE="$(gconftool-2 --get-default-source)" gconftool-2 --makefile-uninstall-rule "$schema" || return 1
    done
}

gnome2_uninstall_schema "$@"
