#!/bin/bash
#
#

gnome2_install_schema() {
    # This is this-is-deprecated
    # return 0
    local schemas=$@
    
    if [ x"$schemas" != x ] && [ -x /usr/bin/gconftool-2 ];then
        for schema in $schemas; do
	        echo "Installing: $schema"
	        GCONF_CONFIG_SOURCE="$(gconftool-2 --get-default-source)" gconftool-2 --makefile-install-rule "$schema" 2>/dev/null
	done
    fi
}

gnome2_install_schema $@
