#!/bin/bash
#
#

gnome2_install_schema() {
    # This is this-is-deprecated
    # return 0
    local schemas="$@"
    
    for schema in $schemas; do
	    echo "Installing: $schema"
	    GCONF_CONFIG_SOURCE="$(gconftool-2 --get-default-source)" gconftool-2 --makefile-install-rule "$schema" || return 1
	done
}

gnome2_install_schema "$@"
