#!/bin/bash
#
#

# Updates Gtk+ icon cache files under /usr/share/icons if the current pbs
# have installed anything under that location.
gnome2_icon_cache_update() {
    local dir=""
    #gnome2_icon_cache_update /usr/share/icons/titans|titans
    local updater="$(type -p gtk-update-icon-cache 2> /dev/null)"
    if [ "x$*" = "x" ]; then
        dir="/usr/share/icons/hicolor"
    else
        while [ "x$1" != "x" ]; do
            [ ! -d "$1" ] && dir+="/usr/share/icons/"${1##*/}" " || dir+="$1 "
            shift
        done
    fi
    echo "Updating icons cache: $dir"
    "$updater" -f -q -t $dir
}

gnome2_icon_cache_update $@

