#!/bin/bash
#
#

gnome2_uninstall_schema() {
    #this is this-is-deprecated
    #return 0
    local schemas="$@"
    if [ x"$schemas" != x ] && [ -x /usr/bin/gconftool-2 ];then
        for schema in $schemas; do
	    echo "Uninstalling: $schema"
	    GCONF_CONFIG_SOURCE="$(gconftool-2 --get-default-source)" \
	      gconftool-2 --makefile-uninstall-rule "$schema" >/dev/null
        done
    fi
}

gnome2_uninstall_schema $@

