#!/bin/bash
#
#

gnome2_uninstall_mine() {
    local mines="$@"
    for mine in $mines; do
	    echo "Uninstalling: $mine"
	    xdg-mime uninstall --mode system "$mine" || return 1
	done
}

gnome2_uninstall_mine "$@"
