#!/bin/bash
#
#

mate_install_schema() {
    local schemas="$@"
    if [ x"$schemas" != x ] && [ -x /usr/bin/mateconftool-2 ];then
        for schema in $schemas; do
            echo "Installing: $schema"
   	        MATECONF_CONFIG_SOURCE="$(mateconftool-2 --get-default-source)" \
	          mateconftool-2 --makefile-install-rule "$schema"  >/dev/null
        done
    fi
}

mate_install_schema $@
