#!/bin/bash
#
#

mate_uninstall_schema() {
    local schemas="$@"
    if [ x"$schemas" != x ] && [ -x /usr/bin/mateconftool-2 ];then
        for schema in $schemas; do
	        echo "Uninstalling: $schema"
	        MATECONF_CONFIG_SOURCE="$(mateconftool-2 --get-default-source)" \
	           mateconftool-2 --makefile-uninstall-rule "$schema" >/dev/null
        done
    fi
}

mate_uninstall_schema $@

