#!/usr/bin/env python
# -*- coding: utf8 -*-
#
#   Copyright © 2012 ivali.com
#   Maintainer: Zhongxin Huang <huangzhongxin@ivali.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
import ybsutils
import argparse

__version__ = '0.1'


def check_diff(ypk_dir):
    ''' 
    
    '''
    ypks = ybsutils.files_in_dir(ypk_dir, '.ypk', 'version')
    ypkfile = ybsutils.PbsFile()
    for ypk in ypks:
        ypkfile.parse(ypk)
        name, version = ypkfile.name, ypkfile.version + ypkfile.relversion
        if not name in PBSLIB_DICT:
            print '{} {} found, but not in pbslib'.format(name, version)
        else:
            if not version in PBSLIB_DICT[name]:
                print '{} {} found, but not in versions: {}'.format(name, 
                                                      version, 
                                                      ' '.join(PBSLIB_DICT[name]))


if __name__ == '__main__':
    ybsutils.signal_int()
    argvs = sys.argv[1:]
    if not argvs:
        argvs = ['-h']
    desc = 'Checking for differences between pbs_dir and ypk_dir.'
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('-v', '--version', action='store_true',
                        help='Show version')
    parser.add_argument('-p', '--pbs_dir', nargs=1, dest='p', required=True,
                        metavar='pbs_dir', help='path to pbs_dir')
    parser.add_argument('-y', '--ypk_dir', nargs=1, dest='y', required=True,
                        metavar='ypk_dir', help='path to ypk_dir')
    args = parser.parse_args(argvs)
    if args.version: print __version__
    if args.p and args.y:
        pbsdir = ' '.join(args.p)
        ypkdir = ' '.join(args.y)
    print "Parsing pbslib from '{}'...\n".format(pbsdir)
    pbsfiles = ybsutils.files_in_dir(pbsdir, '.pbs')
    if not pbsfiles:
        sys.stderr.write("'.pbs' files not found in '{}'.".format(pbsdir))
        sys.exit(1)
    PBSLIB_DICT = ybsutils.parse_pbslib(pbsdir)
    ypkfiles = ybsutils.files_in_dir(ypkdir, '.ypk')
    if not ypkfiles:
        sys.stderr.write("'.ypk' files not found in '{}'.".format(pbsdir))
        sys.exit(1)
    print "Checking for differences between '{}' and '{}'\n".format(pbsdir, ypkdir) 
    check_diff(ypkdir)
